services:
  # 백엔드 API 서비스
  - type: web
    name: receipt-backend
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./app/backend/Dockerfile
    dockerContext: ./app/backend
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /app
      - key: SELENIUM_HEADLESS
        value: true
      - key: LOG_LEVEL
        value: INFO
      - key: ALLOWED_ORIGINS
        value: https://www.adsketch.info,http://www.adsketch.info
    healthCheckPath: /health

# Frontend는 별도로 Static Site로 배포
# Render 대시보드에서 수동으로 "Static Site" 생성 필요:
# 
# Static Site 설정:
# - Name: receipt-frontend
# - Build Command: cd app/frontend && npm ci && npm run build
# - Publish Directory: app/frontend/dist
# - Environment Variables:
#   - NODE_VERSION: 18
#   - VITE_API_BASE_URL: https://receipt-backend.onrender.com/api/v1